### ISSUE TITLE
Ineffective instruction in Kernel-PMU

### ISSUE THREAD

**Issue by h2th3k** [XKCP/XKCP#100]
https://github.com/XKCP/XKCP/blob/169a433ea71b73d6d1696384b695fb47cdc6b6c9/support/Kernel-PMU/enable_arm_pmu.c#L96

**Comment by gvanas** [comment]
The original subject line was:

>  This is wrong, since when the C bit is written, has no effect. ref: https://developer.arm.com/documentation/ddi0595/2020-12/AArch64-Registers/PMCNTENSET-EL0--Performance-Monitors-Count-Enable-Set-register?lang=en #100

**Comment by h2th3k** [comment]
this is my understanding of the correct order to disable the counter
```c
// reset PMCCNTR_EL0 to zero - cycle counter to zero
asm volatile("MSR PMCR_EL0, %0":: "r" (0x41033004));
// disable Cycle Count Register and access from user space
asm volatile("MSR PMUSERENR_EL0, %0":: "r" (0x00000000));
// reset PMCR_EL0 and disable all event counters and PMCCNTR_EL0 
asm volatile("MSR PMCR_EL0, %0":: "r" (0x41033000));
```

**Comment by h2th3k** [comment]
this is my understanding of correct order to disable the cycle counter:
```c
// reset PMCCNTR_EL0 to zero - cycle counter to zero
asm volatile("MSR PMCR_EL0, %0":: "r" (0x41033004));
// disable Cycle Count Register and access from user space
asm volatile("MSR PMUSERENR_EL0, %0":: "r" (0x00000000));
// reset PMCR_EL0 and disable all event counters and PMCCNTR_EL0 
asm volatile("MSR PMCR_EL0, %0":: "r" (0x41033000));
```

**Comment by h2th3k** [comment]
reopen it here

**Comment by BrunoPrho** [comment]
hi, thanks for your comments.  I understand that

1.   you identify a possible issue in disabling the PMU for Aarch64 from the _enable_arm_pmu.c_. you proposed a correction for _disable_cpu_counters_ in the Aarch64.
2. you been able to enable it  but disabling the counter does not disable it.

Is my understanding correct?

**Comment by h2th3k** [comment]
Correct basically previous solution for writing 0 at C bit for `pmcntenset_el0` will not help disable the counter. You could use my previous updated comment to make it work. 

For enabling part, I haven't checked them properly but the way enabling it is not correct. registers value should be read first then flip the bits afterwards.

**Comment by BrunoPrho** [comment]
Hi, thanks 
I will rebuild or re-use an Aarch64 env. to check the `disable_cpu_counters`. In most of the uses cases, we never disable in fact as users load the kernel and enable the counter (if required) for doing particular cycle measurements for testing purpose sometime only. 
How ever, it is good to have something fully right and I will definitely look at it again. 
Thanks for the heads up

**Comment by BrunoPrho** [comment]
Hi, I have reload a `Cortex A57, RPI 3B+, OpenSUSE 15.0, kerne; 4.12.14`. One of the initial machine used 3 years ago and I am able to load the module (read the PMU) and unload the module (which produce an error as the system can't access the PMU). See the capture. It may indicates that there is different successful implementations so far but from my test on this environment the current implementation is effective.  To be fair, I did not dive again into this topic and as far as required i will read the latest docs. 

Regards

![screenshot](https://user-images.githubusercontent.com/76922633/183389928-8cfffc1f-8afd-499a-b3b1-c10acc783bad.png)
