### ISSUE TITLE
How to test specific function?

### ISSUE THREAD

**Issue by abbydong0417** [XKCP/XKCP#106]
Hi!

I am a student who is using XKCP for a project.
Could someone please tell me how to test Xoodyak function?

Best,

**Comment by abbydong0417** [comment]
I have read the test code and run "make generic64/UnitTests", I don't know how to find the specific function test then.

**Comment by Mohammad-ipv6** [comment]
same here. It seems that more in-depth README file regarding examples and usages can help beginners with the code to see sample output.

**Comment by gvanas** [comment]
What do you want to achieve exactly? The unit tests are testing if the implementation works as expected. To unit test the Xoodyak implementation, run `UnitTests --Xoodyak`. Type `UnitTests --help` for more options.

**Comment by abbydong0417** [comment]
> What do you want to achieve exactly? The unit tests are testing if the implementation works as expected. To unit test the Xoodyak implementation, run `UnitTests --Xoodyak`. Type `UnitTests --help` for more options.

Thanks for ur reply. I reboot everything and try to run everything.
I ran the commands 'make generic64/libXKCP' and 'make generic64/UnitTests' successfully. But I cannot run Unittests or generic64/Unittests command. What's wrong?
<img width="490" alt="Screenshot 2022-11-05 at 18 04 05" src="https://user-images.githubusercontent.com/71556766/200132415-30c12ff6-7c93-48a1-956a-8be78c972f8f.png">
<img width="485" alt="Screenshot 2022-11-05 at 18 04 13" src="https://user-images.githubusercontent.com/71556766/200132416-8194cff2-5e9f-4210-a873-0d27d755aec7.png">
<img width="444" alt="Screenshot 2022-11-05 at 18 04 24" src="https://user-images.githubusercontent.com/71556766/200132417-c3df15eb-0556-457b-b040-71b9ceb5c1f2.png">

**Comment by abbydong0417** [comment]
It is solved. Thanks!
