### ISSUE TITLE
Xoodyak for key generation

### ISSUE THREAD

**Issue by abbydong0417** [XKCP/XKCP#107]
Hi Keccak Team,

Can Xoodyak used for public and private key generation? If so, could you please give some extended materials for that?
Thanks.

**Comment by jedisct1** [comment]
Xoodyak is for symmetric cryptography.

So, not, it's not the right tool if you need public and private keys.

But you can use any existing key exchange mechanism, derive a shared 128-bit key from it and use that key with xoodyak to encrypt and authenticate data.
