### ISSUE TITLE
Undefined reference

### ISSUE THREAD

**Issue by lashahub** [XKCP/XKCP#108]
I build the XKCP library using `make generic64/libXKCP.a`. After that I placed the `.a` file and headers in my project folder.
I use `target_include_directories()` and `target_link_libraries()` in CMake for including headers and linking the library file. CMake configuration succeeds without error, but if I use `SHA3_256(unsigned char*, unsigned char const*, unsigned long)` function from `SimpleFIPS202.h` I get a linking error during the actual project build: `undefined reference to SHA3_256`. Clearly the `.a` file as well as header files were found, and the library was linked. Why do I get this error? What could be causing this linking error in the final build stage? I'm using C++20, CMake 3.23, running on WSL Kali-Linux (GCC compiler).

**Comment by gvanas** [comment]
You mention C++20; does it mean that you are calling `SHA3_256()` from C++ code? If so, can you try with including `SimpleFIPS202.h` inside a `extern "C"` construct?

**Comment by lashahub** [comment]
It worked thank you!
