### ISSUE TITLE
ARMv7M compilation issue

### ISSUE THREAD

**Issue by rben-dev** [XKCP/XKCP#125]
Hi,

There seems to be an issue when compiling for `ARMv7M`, with missing symbols. When using `arm-linux-gnueabi-gcc` for the `cortex-m3` target (so indeed and `armv7-m` target), many `Ket` related symbols are undeclared and undefined, yielding compilation warnings and linking errors:

```
Ketjev2.c:(.text+0x832): undefined reference to `KetMn_StateOverwrite'
/usr/lib/gcc-cross/arm-linux-gnueabi/13/../../../../arm-linux-gnueabi/bin/ld: Ketjev2.c:(.text+0x83e): undefined reference to `KetMn_StateOverwrite'
...
Ketjev2.c:(.text+0x8fc): undefined reference to `KetMn_StateAddByte'
/usr/lib/gcc-cross/arm-linux-gnueabi/13/../../../../arm-linux-gnueabi/bin/ld: Ketjev2.c:(.text+0x90c): undefined reference to `KetMn_Step'
/usr/lib/gcc-cross/arm-linux-gnueabi/13/../../../../arm-linux-gnueabi/bin/ld: Ketjev2.c:(.text+0x928): undefined reference to `KetMn_FeedAssociatedDataBlocks'
/usr/lib/gcc-cross/arm-linux-gnueabi/13/../../../../arm-linux-gnueabi/bin/ld: Ketjev2.c:(.text+0x948): undefined reference to `KetMn_StateAddByte'
...
```

This comes from the fact that in `lib/low/Ketje/OptimizedAsmARM/Ket.h`, `XKCP_has_KeccakP1600` is not defined while the generated `Makefiles` for the target `ARMv7M/UnitTests` choose to use `KeccakP1600` anyways. Any insights on the issue?

Thanks in advance,

**Comment by gvanas** [comment]
Before looking into this issue in more details, do you really want to use Ketje?

It is in our plans to remove Ketje and Keyak from the XKCP, as Xoofff and Xoodyak are better alternatives, see [this discussion](https://github.com/XKCP/XKCP/discussions/113). So if you do not really need Ketje, I could remove it sooner rather than later, thereby "solving" this current issue. 😇

**Comment by rben-dev** [comment]
Thanks for the answer. Indeed, I do not really want to use Ketje as I stumbled upon this error when going through various cross-compilation tests (for a hopefully soon to come CI for XKCP :-)).
Sorry for missing the discussion you point out!

Removing Ketje suits me fine :-)

**Comment by gvanas** [comment]
I just pushed a commit that removes Ketje and Keyak. Can you confirm if it solves this issue?

**Comment by rben-dev** [comment]
I confirm that fetching the last commits indeed solves the issue! Thanks!
