### ISSUE TITLE
Possible performance gain for code with state in registers

### ISSUE THREAD

**Issue by forthy42** [XKCP/XKCP#127]
In several of the vectorized low-level implementations, the entire Keccak state fits into registers (AVX2, AVX512, ARMv8/Neon), and other registers may be used as inputs for vector functions, e.g. for permutations, and don't change after loading.  In this case, the operations are now

loop over large block {
absorb memory -> state in memory
load state from memory -> registers
set up other registers
permute^rounds
write state -> memory
state in memory -> extract to some other memory
}

This does not sound right from a performance point of view; memory accesses are costly, especially since the state is quite large (200 bytes).  I suggest

set up other registers
load state from memory -> registers OR initialize registers (if we start with state=0)
loop over large block {
absorb memory -> registers (depending on mode)
permute^rounds
extract/encrypt/decrypt register -> memory (depending on mode)
increment pointers
}
write state -> memory

This is, from a C point of view, non-structural factoring (you can't keep values in registers between function calls), so it all has to be done in macros.  Assembly has to be inline assembly.  The benefit is likely to be greater for 12 rounds than for 24 rounds.

I've some code where I use KeccakP[1600,2] as part of passphrase deviation function over a larger chunk of memory in encrypt mode (several times encrypting the same memory), and the benefit there is probably much higher.

Another optimization worth to consider within extract/add/overwrite is __builtin_bswap64() for big endian, and use a single conditional macro definition similar to the host><network byte order macros in the socket interface (it is one single macro, htonl/ntohl are doing the same thing, even on weird mixed-byte-order machines like the PDP-11).

**Comment by gvanas** [comment]
Thanks for your feedback!

There are implementations of Keccak-P[1600] that do follow this idea in the "FastLoop" functions. See, for instance, [the KeccakF1600_FastLoop_Absorb() function](https://github.com/XKCP/XKCP/blob/d1d7bbe799d10f67d44e46bea232d03c74a7ee77/lib/low/KeccakP-1600/AVX2/KeccakP-1600-AVX2.s#L661) in the AVX2 implementation. I checked the same is true for AVX512 and ARMv7A-NEON.

But do you see other cases that would benefit from such an optimization?
