### ISSUE TITLE
Customized Build with cSHAKE

### ISSUE THREAD

**Issue by kc2rxo** [XKCP/XKCP#136]
Hello,

I am attempting to add another target to make a specific build following the guide in `doc/HOWTO-customize.build`. I am targeting a generic 32-bit micro controller and only need the cSHAKE functions for my application.

I added `<target name="just-cshake.a" inherits="SP800-185 K1600-plain-32bits-inplace"/>` to the bottom of the `HOWTO` file and my target does not appear in the list when running `make`. The build errors out when attempting to run `make just-cshake.a` with: `make: *** No rule to make target 'just-cshake.a'.  Stop.`

Is there something I am missing?

**Comment by kc2rxo** [comment]
I have found that if I add the line to `Makefile.build` instead of `doc/HOWTO-customize.build` it compiles.

However the only successful compilation I have had is as a static lib (`.a`). Ending with anything else (like `.pack`) results in a new error:

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

**Comment by gvanas** [comment]
Strange. I just tested this on my PC, added the exact same `<target …` line to `doc/HOWTO-customize.build`, and `make just-cshake.a` worked as expected. And so did `make just-cshake.a.pack`. Maybe something needed to be refreshed with `make clean`?

About the error `undefined reference to 'main'`, having just cSHAKE does not provide any `main()` function and GCC will complain when trying to make an executable.

**Comment by kc2rxo** [comment]
I ended up getting it working. I found that I misunderstood that `.pack` was appended to not replacing the extension (`.a`). As such I suspect that the build system was attempting to build something non-existent thus creating the `main` error I experienced.
