### ISSUE TITLE
Xoodoo_Permute_Nrounds API type issue on some platforms

### ISSUE THREAD

**Issue by rben-dev** [XKCP/XKCP#147]
Hi,

The Xoodoo API is defined like this in the exposed header:
`void Xoodoo_Permute_Nrounds(Xoodoo_plain8_state *state, unsigned int nrounds);`

When it is implemented for various platforms, it uses the `uint32_t` type:
`void Xoodoo_Permute_Nrounds(Xoodoo_align128plain32_state *state, uint32_t nr)`

While `uint32_t` can indeed match `unsigned int` on many platforms, some can define the ABI and the two types might not match: for instance, on `risc-v rv32` with the `ilp32` ABI the `uint32_t` type will match a `long unsigned int`. This provokes a compilation error when compiling, e.g. for `rv32`, because the function prototype is not matching the definition.

The solution would be either to define the number of rounds as a `uint32_t` with the advantage of fixed size (but bringing `stdint` to the exposed API which does not seem to be the spirit), or implement it as `unsigned int` in the implementation and accept the possible variable type size depending on the platform.

Regards,

**Comment by gvanas** [comment]
Thanks for pointing this out. I would be in favor of the second proposal, i.e., implement it as `unsigned int`.

**Comment by rben-dev** [comment]
Thanks for the feedback: PR #148 attempts to fix this with the `unsigned int` way.

Regards,
