### ISSUE TITLE
KeccakP1600 ARMv7A possible bug

### ISSUE THREAD

**Issue by andrehcmoraes** [XKCP/XKCP#22]
I have noticed what I believe is a bug in the KeccakP-1600 implementation for ARMv7A.

In the file [/SnP/KeccakP-1600/OptimizedAsmARM/KeccakP-1600-armv7a-le-neon-gcc.s](https://github.com/gvanas/KeccakCodePackage/blob/master/SnP/KeccakP-1600/OptimizedAsmARM/KeccakP-1600-armv7a-le-neon-gcc.s) at lines 477 and 489, shouldn't it be:

`b       KeccakP1600_Permute`

Instead of

`b       KeccakP1600_PermuteAsmOnly`

**Comment by gvanas** [comment]
We will have a look and try to fix this in the coming days.

Thanks for catching this issue.
