### ISSUE TITLE
Easy AVX2 example

### ISSUE THREAD

**Issue by robertdavidgraham** [XKCP/XKCP#34]
I've been beating my ahead against trying to decipher how to use the parallel routines.

What I'm looking for is to take a standard SHA3 function hypothetically like:

    unsigned char result[32];
    unsigned char *buffer;
    sha3_256(result, buffer, buffer_length);

and then make it parallel:

    unsigned char results[8][32];
    unsigned char *buffers[8];
    sha3_256_parallel(results, buffers, buffer_length, 8);

You've got primitives I can use to build this, but I don't really understand them. It appears my steps might be:
- allocate memory (based on size/alignment macros)
- KeccakP1600times8_InitializeAll()
- pad my data and copy into the "lanes" format that you want
- KeccakP1600times8_AddLanesAll()
- KeccakP1600times8_PermuteAll_24rounds()
- KeccakP1600times8_ExtractLanesAll() to get the results

Do you have any example function that does all this? Something with test vectors I can test against normal SHA3 standard?

**Comment by gvanas** [comment]
There is an example of this in the implementation of ParallelHash. ParallelHash128 (resp. 256) internally uses parallel evaluations of SHAKE128 (resp. 256). So you might have a look at lines 254-280 of `Modes/SP800-185.inc`.

Note that the `KeccakP1600timesX_AddLanesAll()` function assumes that the data are regularly spread in a big buffer. If you have separate buffers (as you wrote it in your example), you could also use a loop over `KeccakP1600timesX_AddBytes()`.

If this does not help, I can write a small example more dedicated to your case, but let's first see if the example of ParallelHash is useful.
