### ISSUE TITLE
Archive old repo

### ISSUE THREAD

**Issue by ildyria** [XKCP/XKCP#45]
I see that https://github.com/KeccakTeam/KeccakCodePackage is *"17 commits behind XKCP:master."*

Maybe it would be a good idea to add a note that it moved [here](https://github.com/XKCP/XKCP) and to [Archive](https://github.com/KeccakTeam/KeccakCodePackage/settings) (just before the *delete* option) the repository ?

**Comment by gvanas** [comment]
Yes, but it also says it was forked from XKCP/XKCP. Isn't that a sufficient link back to the main repository?
