### ISSUE TITLE
Missing MarsupilamiFourteen, and hypothetical 16-round version of KangarooTwelve

### ISSUE THREAD

**Issue by DonaldTsang** [XKCP/XKCP#46]
Is it possible to create a version of KangarooTwelve with:
- capacity/chaining value of 128 bytes (the `c` variable in the end function of Python implementation)
- 72 bytes sponge rate (the `rateInBytes` variable in F in the Python implementation)
- 16-rounds (`KeccakP1600(state, 12)` with 16 instead of 12 in the Python implementation)

**Comment by DonaldTsang** [comment]
@ildyria Was having this idea of a progressive hash similar to Skein, since Skein has 256bit, 512bit and 1024bit modes. Also MarsupilamiFourteen, which is in the K12 documentation, is not in XKCP.

**Comment by DonaldTsang** [comment]
@ildyria Still waiting for the MarsupilamiFourteen implementation that is referenced in the document

**Comment by DonaldTsang** [comment]
@ildyria Now I am planning to request people who know C or Rust to implement KangarooTwelve and MarsupilamiFourteen

**Comment by ildyria** [comment]
1. **You should never rename an issue to make it about something completely different.**
2. KangarooTwelve seems to be already available in Rust: https://libraries.io/cargo/k12
If you want MarsupilamiFourteen, I suggest you bother the maintainer of this package.

**Comment by DonaldTsang** [comment]
@ildyria sorry, maybe this issue should be closed and another should open?

**Comment by ildyria** [comment]
That would be the standard practice. :+1:
