### ISSUE TITLE
bug in AVX512 implementation of KeccakP1600_12rounds

### ISSUE THREAD

**Issue by jwitmann** [XKCP/XKCP#49]
Hi,

Path: lib\low\KeccakP-1600\OptimizedAVX512c\KeccakP-1600-AVX512.c

Unless I am mistaken, the function **KeccakP1600_12rounds_FastLoop_Absorb** has a small mistake (copy and paste I presume). At line 615, you do a **KeccakP1600_Permute_24rounds(state)**, I think it should be K**eccakP1600_Permute_12rounds(state)**.

Thanks,
Jerome

**Comment by gvanas** [comment]
Hi Jerome,

Good catch, many thanks!

Kind regards,
Gilles

**Comment by gvanas** [comment]
Note that the assembly code in `OptimizedAVX512a/KeccakP-1600-AVX512.s` is faster, and that's the one that is selected when doing `make SkylakeX/…` (for your information).
