### ISSUE TITLE
cSHAKExxx without customization not equal to SHAKExxx

### ISSUE THREAD

**Issue by HayoBaan** [XKCP/XKCP#51]
The NIST specification stipulates that cSHAKExxx should produce the output of SHAKExxx when no customization is specified. This does not seem to be the case with the current implementation in XKCP.

Is this an error or is this by design (i.e. user code should not use cSHAKE if there is no customization)?

**Comment by gvanas** [comment]
You're right, thanks, this is a bug indeed. We will fix this.
