### ISSUE TITLE
Discussion : Extended sponge squeeze

### ISSUE THREAD

**Issue by d3x0r** [XKCP/XKCP#55]
Hello, just wanted to post an observation I had.
I have a PRNG I call 'salty_random_generator'.  It basically manages the resulting hash 'entropy pool' and draws off small numbers of bits at a time.  It has a callback, which for each block of hash, it can request addition user salt to mix in... (this is sort of a bad description); yes this is not how/why hashing functions were designed, but after doing a lot of various tests, they do make really good number generators, when taken as a stream of bits.

1) SRNG = createGenerator( saltCallback, saltUserData )
2) GetBits( SRNG, 2 ); 
2a)  SRNG has 0 bits availalbe, call saltCallback to get some salt, hash the salt with SHA1/2-256/2-512/3(keccak)/K12 .... so the 'entropy' returned is 128-512 bits... (so getting 2 bits at a time as above, is quite a few calls before needing to generate more 'entropy'
3) repeat getBits( SRNG, 2 );
 3a) SRNG needs more bits, take the current hash, feed it into the hashing function, again calling user salt function to mix in more. ... so it works sort of in a OFB sort of mode (also injecting salt from out of band, that's not part of the data)

right? with me?  SHA3 version is quite a bit slower than SHA2-256(or 512, which is itself slower than SHA2-256; but; provides a larger pool of random entropy bits to return so... trade off is pretty good).

I have a test program, which gets 200,000,000 2 bit values, and counts 1) how many times each value happens, 2) how many times each value follows some other value   ( 0,1,2,3;  should each be followed by a 0,1,2 or 3 an equal chance )  The test program also does 7 bits (0-127), and 16 bits on 64 bit system (4G integer entries to increment; just the page swapping in the counting logic slows down the test :)  ).

I realized that K12 is part of a XOF family (so's the SHA3, but didn't test that), so I could, in theory, just call the user getSalt callback once, and then run the hash, squeezing the sponge continually (much more than I had absorbed into the sponge).  This leads to patterns that are more probable in a squence to appear...

in the 2 bit test, 500,000 is the average, and 

( A 'good' output )
```
0 = 50012002 
1 = 50003734 
2 = 49997510 
3 = 49986754 

0,0 = 12511301 
0,1 = 12499954 
0,2 = 12500744 
0,3 = 12500003 
1,0 = 12504284 
1,1 = 12505993 
1,2 = 12496670 
1,3 = 12496786 
2,0 = 12499436 
2,1 = 12501219 
2,2 = 12501385 
2,3 = 12495470 
3,0 = 12496981 
3,1 = 12496567 
3,2 = 12498711 
3,3 = 12494495 
2bits 200000000 in 5640ms
```

if I just feed an initial entropy, and squeeze all the bits out...

```
0 = 54687500              0 = 49218750 
1 = 37500000              1 = 54687500 
2 = 50781250              2 = 50781250 
3 = 57031250              3 = 45312500 

0,0 = 17187500            0,0 = 13281250 
0,1 = 12500000            0,1 = 12500000 
0,2 = 11718750            0,2 = 14062500 
0,3 = 13281250            0,3 = 9375000 
1,0 = 10937500            1,0 = 11718750 
1,1 = 4687500             1,1 = 17187500 
1,2 = 8593750             1,2 = 14843749 
1,3 = 13281250            1,3 = 10937500 
2,0 = 10937500            2,0 = 13281250 
2,1 = 9375000             2,1 = 14843750 
2,2 = 14062500            2,2 = 10937500 
2,3 = 16406250            2,3 = 11718750 
3,0 = 15625000            3,0 = 10937500 
3,1 = 10937500            3,1 = 10156250 
3,2 = 16406250            3,2 = 10937500 
3,3 = 14062499            3,3 = 13281250 
2bits 200000000 in 5093ms  2bits 200000000 in 5100ms

```

The initial seed is like GetTickCount() /* current millisecond */

Also, it seems, I'm really ending up using the slowest side of this algorithm?  That is, I have short messages to input (int32 with tick, maybe a few floats for x,y,z position in space) and want a long output.... like switching to just the squeeze was slightly faster, but not significantly.

So I have some questions : how long is the cycle of the squeeze on the sponge?  Can the squeeze side be optimized further?  Maybe putting more work on the initial input side?

I'm using this salty-random-generator to generate procedural terrains/etc, so having a PRNG I can seed is of primary concern.  Adding the salt callback allows me to also start from the same point, and fork a RNG stream (make a copy of it really, and start feeding it new salt).  Also, if the salt was like /dev/urandom bytes, it's a way of just mixing in entropy progressively, increasing the overall entropic characteristics 

---
(Edit)
I'm using a output size of 64 bytes (512 bits) ... K12-512 sort-of.

I was reflecting that when walking through the code, the squeeze does a rounds12; kinda like feeding new input; so if I just take the output, and feed it back in, it could have the same effect, without adding the additional entropy.   (K12-512-OFB (sort of, probably not, but I'm calling it that.))

It does not have an issue.  

```
		KangarooTwelve_Initialize( &ctx->f.K12i, K12_DIGEST_SIZE );

		r = KangarooTwelve_Final( &ctx->f.K12i, ctx->s.entropy4, NULL, 0 );
     /* use bits from entropy, until need more, then */
		KangarooTwelve_Initialize( &ctx->f.K12i, K12_DIGEST_SIZE );
		KangarooTwelve_Update( &ctx->f.K12i, ctx->s.entropy4, K12_DIGEST_SIZE );

		r = KangarooTwelve_Final( &ctx->f.K12i, ctx->s.entropy4, NULL, 0 );
     /* use bits from entropy, until need more, then */
		KangarooTwelve_Initialize( &ctx->f.K12i, K12_DIGEST_SIZE );
		KangarooTwelve_Update( &ctx->f.K12i, ctx->s.entropy4, K12_DIGEST_SIZE );

		r = KangarooTwelve_Final( &ctx->f.K12i, ctx->s.entropy4, NULL, 0 );
     /* use bits from entropy, until need more, then */
		KangarooTwelve_Initialize( &ctx->f.K12i, K12_DIGEST_SIZE );
		KangarooTwelve_Update( &ctx->f.K12i, ctx->s.entropy4, K12_DIGEST_SIZE );

/* etc.  It is actually left in this state, so when there is salt... */

		KangarooTwelve_Update( &ctx->f.K12i, ctx->salt, ctx->salt_size );
		r = KangarooTwelve_Final( &ctx->f.K12i, ctx->s.entropy4, NULL, 0 );
		KangarooTwelve_Initialize( &ctx->f.K12i, K12_DIGEST_SIZE );
		KangarooTwelve_Update( &ctx->f.K12i, ctx->s.entropy4, K12_DIGEST_SIZE );

     /* use bits from entropy, until need more, then */

```

(Edit2)

This is example code that has non-randomness
```
		KangarooTwelve_Initialize( &ctx->f.K12i, 0 );
		KangarooTwelve_Update( &ctx->f.K12i, ctx->salt, ctx->salt_size );
		r = KangarooTwelve_Final( &ctx->f.K12i, ctx->s.entropy4, NULL, 0 );
		KangarooTwelve_Squeeze( &ctx->f.K12i, ctx->s.entropy4, K12_DIGEST_SIZE );
/* use bits*/
		KangarooTwelve_Squeeze( &ctx->f.K12i, ctx->s.entropy4, K12_DIGEST_SIZE );
/* use bits*/
		KangarooTwelve_Squeeze( &ctx->f.K12i, ctx->s.entropy4, K12_DIGEST_SIZE );
/* use bits*/
		KangarooTwelve_Squeeze( &ctx->f.K12i, ctx->s.entropy4, K12_DIGEST_SIZE );
/* use bits*/
```

**Comment by gvanas** [comment]
Dear Jim,

Thanks for your comments.

In your last example, what is the value of `K12_DIGEST_SIZE`?

On a related note, did you have a look at [KeccakPRG](https://github.com/XKCP/XKCP/blob/master/doc/KeccakPRG-documentation.h)?

Kind regards,
Gilles

**Comment by d3x0r** [comment]
K12_DIGEST_SIZE is  64 bytes (512 bits)

nope, didn't see PRG :)

**Comment by gvanas** [comment]
I tried to [reproduce](https://gist.github.com/gvanas/15cfed95e3bddfbb07bb8f80aa98f510) your code that "has non-randomness", but did not notice any significant bias.

**Comment by d3x0r** [comment]
Ya, that looks approximately like it... Hmm...
and ya; doesn't show the same.... I'll have to try it again.

**Comment by d3x0r** [comment]
Strange.  I don't have the exact code now that was failing, so it's hard for me to say exactly what happened.  I optioned in (this time) using a long-squeeze mode, and it's remaining smoothly random.
Thank you for your time. 😄 

It does increase performance a lot to be able to use long squeeze; (limited it to 32768 bits)

Just some stats....

```
K12 (long squeeze - 32768 bits) (about 2X speed, near 4x SHA1)
                       ms     per-ms                
1   bits 250,000,000 in  2257   110766
2   bits 250,000,000 in  2245   111358
4   bits 250,000,000 in  2428   102965
16  bits 250,000,000 in  3226   77495
256 bits 100,000,000 in 11471   8717

K12 (repeated-seeding every 512 bits)
                       ms     per-ms
1   bits 250,000,000 in  2323   107619
2   bits 250,000,000 in  2470   101214
4   bits 250,000,000 in  2792   89541
16  bits 250,000,000 in  5068   49329
256 bits 100,000,000 in 22577   4429


SHA1 (the fastest(previous) generator - 256 bit blocks)
1   bits 250,000,000 in  2543   98309
2   bits 250,000,000 in  3143   79541
4   bits 250,000,000 in  4055   61652
16  bits 250,000,000 in 10427   23976
256 bits 100,000,000 in 57216   1747


```
