### ISSUE TITLE
Makefile.build:1: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by noloader** [XKCP/XKCP#56]
According to the readme:

> The list of targets can be found at the end of Makefile.build or by running make without parameters.

```
$ git clone https://github.com/XKCP/XKCP.git
$ cd XKCP

XKCP$ make -f Makefile.build
Makefile.build:1: *** missing separator.  Stop.
```

It looks like an XML file, not a makefile.

To cut to the chase, I'm trying to understand what is needed for the SSE2 build located in `.../lib/low/KeccakP-1600-times2/SIMD128`:

```
$ make | grep SSE
$
```

**Comment by gvanas** [comment]
To answer your first question, `Makefile.build` is not a makefile indeed, but `Makefile` is using the information located in it. So `make -f Makefile` or just `make` should do it.

Regarding the code that you mention, its purpose is to compute two Keccak-f[1600]'s in parallel using SSE2 vector instructions. It is included in the Nehalem, SandyBridge and Haswell implementation selections. E.g., `make Haswell/KeccakTests`, `make Haswell/libkeccak.a` or `make Haswell/libkeccak.so` will make test code, a static library or a dynamic library with implementations selected for Haswell (so including the SSE2 code).

I hope this helps.
