### ISSUE TITLE
Can't compile for ARMv7M

### ISSUE THREAD

**Issue by FiorixF1** [XKCP/XKCP#60]
I'm trying to compile for ARMv7M just by doing make ARMv7M/libkeccak.a, but when linking with the assembly scripts in the library I get some errors such as "bad instruction" for each "align 4" and "shift expression too large" for each eors instruction. I assumed it was easy to compile, while actually I'm wasting days just compiling for these problems.

**Comment by gvanas** [comment]
Of course, it is not the purpose to waste days on such problems. To be able to help you, can you give more details on which platform and compiler you are using?

**Comment by gvanas** [comment]
We could indeed reproduce the problem and Ronny fixed it. Does it work on your side?

**Comment by FiorixF1** [comment]
The errors referred to Xoodoo modules, so indeed this update fixed it

**Comment by gvanas** [comment]
Thanks for your feedback!
