### ISSUE TITLE
Test Xoodyak_aead_SelfTest fails

### ISSUE THREAD

**Issue by llsoft2000** [XKCP/XKCP#65]
Hi,

I compiled the Xoodyak AEAD selftest and ran them. Unfortunately, the selftest fails because encrypted data differs from expected output:
`!!! The output of crypto_aead_encrypt() is not as expected.`

I ran the tests in two configurations:
* `make Xoodyak_aead_SelfTest/XooReference`
`bin/Xoodyak_aead_SelfTest/XooReference`
* `make Xoodyak_aead_SelfTest/XooOptimized32`
`bin/Xoodyak_aead_SelfTest/XooOptimized32`

I could not figure out if the test fails due to the test vector or the implementation?

Thanks,
llsoft

**Comment by gvanas** [comment]
Thanks for the report. Indeed, I could reproduce the problem that you mention.

We will try to fix it, but it may some more time because of the holidays.

Kind regards,
GIlles

**Comment by gvanas** [comment]
Thanks for your patience. The implementation is correct, but the test vector was out of sync.
