### ISSUE TITLE
make KeccakSum being able to take data from stdin

### ISSUE THREAD

**Issue by lvd2** [XKCP/XKCP#71]
This is useful for measuring speed like this:
`dd if=/dev/zero bs=1048576 count=1024 | KeccakSum --from-stdin`

**Comment by gvanas** [comment]
If the goal is to measure speed, there are easier ways. One is to build the `Benchmarks` executable and have it produce a report. Another is to write a few lines of code that does the same as your example, e.g., see the `bench1GB()` function in [K12](https://github.com/XKCP/K12/blob/master/tests/main.c).

**Comment by lvd2** [comment]
1. There is an uniform way of benchmarking different hash executables like this:
`
dd if=/dev/zero | md5sum
dd if=/dev/zero | KeccakSum # not supported
`
while it is not accurate, since the time to generate zeros and pass them through to the stdin is also accounted, it is still convenient to compare implemenations

2. Another common use-case is the following:
`
xz -dkc filename.xz | md5sum
xz -dkx filename.xz | KeccakSum # not supported
`
to check integrity of the compressed file

**Comment by gvanas** [comment]
There are indeed valid use cases that would make this worth implementing, so let's do it. If you feel up to it, let me know. Otherwise, I'll have a look but I cannot promise when I will be able to do this.

**Comment by lvd2** [comment]
here is the pull request: https://github.com/XKCP/XKCP/pull/72

**Comment by gvanas** [comment]
Solved in #72.

PS: If you want something fast, try

```
dd if=/dev/zero bs=1M count=1k | KeccakSum --k12
```
