### ISSUE TITLE
AVX builds broken on x86

### ISSUE THREAD

**Issue by namazso** [XKCP/XKCP#76]
https://github.com/XKCP/XKCP/blob/master/lib/low/Xoodoo/SSE2/Xoodyak-full-block-SIMD128.c#L337

this call to _mm_insert_epi64 is invalid. This intrinsic encodes the [PINSRQ](https://www.felixcloutier.com/x86/pinsrb:pinsrd:pinsrq) instruction which is not valid in legacy mode

The actual error i received is `..\..\lib\low\Xoodoo\SSE2\Xoodyak-full-block-SIMD128.c(337,12): error : assigning to 'V128' (aka '__m128i') from incompatible type 'int'` because the intrinsic in smmintrin.h is ifdef-guarded.

**Comment by namazso** [comment]
Additionally, AVX2 and AVX512 is also broken:
`..\..\lib\low\KeccakP-1600-times4\AVX2\KeccakP-1600-times4-SIMD256.c(1274,13): error : assigning to 'V256' (aka '__m256i') from incompatible type 'int'`
and
`..\..\lib\low\Xoodoo\AVX512\Xoodyak-full-block-SIMD512.c(314,12): error : assigning to 'V128' (aka '__m128i') from incompatible type 'int'`

Are these extensions not supported on x86?

**Comment by gvanas** [comment]
Thanks for the report. Indeed, I never tested these implementations on 32-bit x86.

Does it still make sense these days to support 32-bit x86 together with AVX, AVX2 or AVX512?

If you think so, I can have a closer look, but if you know how to fix this quickly, do not hesitate to do a PR.

**Comment by namazso** [comment]
Windows software still often ships as x86 so there's definitely an use case here. Whether it's worth it, I'm not sure.

>if you know how to fix this quickly, do not hesitate to do a PR.

Unfortunately my experience with the vector instructions / intrinsics is limited to knowledge of their existance, so can't help with that.

**Comment by gvanas** [comment]
I just pushed a fix for this. It works correctly on my machine, but do not hesitate to reopen if needed.
