### ISSUE TITLE
ARMv8A vcxproj broken

### ISSUE THREAD

**Issue by namazso** [XKCP/XKCP#77]
`make ARMv8A/libXKCP.a.vcxproj` generates a vcxproj with no ARM64 target

In addition, generic32 and generic64 also has no ARM64 target

**Comment by namazso** [comment]
`sed -i 's/x64/ARM64/g' XKCP/bin/VC/ARMv8A_libXKCP.a.vcxproj` works as a bandaid fix for now, after that it works like all the others

**Comment by gvanas** [comment]
Hi again. Indeed, I don't have access to a Windows machine with a ARMv8A processor, so I never tried to build a Visual Studio project on such a  machine.

Do you confirm that replacing x64 with ARM64 alone solves the issue? If so, I can adapt the build system and add support to this.

**Comment by namazso** [comment]
Yes, KeccakSum builds and runs well after doing that simple string replacement.  Doing it on `ARMv8A_libXKCP.a.vcxproj` results in same errors as it produces other platforms, and [my build flags](https://github.com/namazso/OpenHashTab/blob/master/build-xkcp.bat) that make it compile as static library on x64 / Win32 work well after that, so I'd count that as a fix too (the reason none build by default is lack of `ConfigurationType` being set to `StaticLibrary`).

**Comment by gvanas** [comment]
I added support for libraries and for the ARMv8A platform in the generation of Visual Studio project files on the `vcxproj` branch. 

Could you check if that works well on your side? The generation of a `.lib` file seems to work fine here, but I could not test the ARMv8A part.

**Comment by namazso** [comment]
> but I could not test the ARMv8A part.

you can install the ARM64 toolchain in visual studio installer in case that's the only thing holding you back.

anyways, i tested it, both seem to work.

however: 

https://github.com/XKCP/XKCP/commit/9e046fae3666abe950f32f6abbbbb1f07be0339a#diff-59318b6473585d00a2e5aa8f6037a72f4f8ee9103bd970d017a564877f3deed5R43-R52

this setting is not related to whether you're building a static library. this one is about how the CRT is linked, and in case of a static library it must match with whatever the other modules getting linked are built with. So if you have MyProject trying to use libXKCP.lib they must match, and all four options are valid. I'd suggest making it overridable with an msbuild property and defaulting to the dll one. This could be achieved with something like this:
```xml
	<PropertyGroup Condition="'$(RuntimeLibrary)'==''">
		<RuntimeLibrary Condition="'$(Configuration)'=='Debug'">MultiThreadedDebugDll</RuntimeLibrary>
		<RuntimeLibrary Condition="'$(Configuration)'=='Release'">MultiThreadedDll</RuntimeLibrary>
	</PropertyGroup>
```

added under Project tag and then just using `<RuntimeLibrary>$(RuntimeLibrary)</RuntimeLibrary>` under ClCompile. This way you can easily override it with `-p:RuntimeLibrary=MultiThreaded` passed to msbuild

**Comment by gvanas** [comment]
OK, thanks for the tip, I didn't know about the ARM64 toolchain.

I implemented your suggestion, still on the `vcxproj` branch. If all OK for you, I will squash-merge it onto `master` and close this issue.

**Comment by namazso** [comment]
looks all good by me
