### ISSUE TITLE
AVX512 build is broken on Linux with gcc

### ISSUE THREAD

**Issue by larryhastings** [XKCP/XKCP#78]
I can't build either `AVX512/KeccakSum` or `AVX512/libXKCP.so`.  I get the following errors:

`lib/low/KeccakP-1600-times2/AVX512/KeccakP-1600-times2-SIMD512.c: In function ‘KeccakP1600times2_AddLanesAll’:
lib/low/KeccakP-1600-times2/AVX512/KeccakP-1600-times2-SIMD512.c:192:62: warning: AVX512F vector return without AVX512F enabled changes the ABI [-Wpsabi]
  192 |     #define Add_In4( argIndex )  stateAsLanes512[argIndex/4] = XOR512(stateAsLanes512[argIndex/4], LOAD_GATHER8_64(index512, dataAsLanes+argIndex))
      |                                                              ^
lib/low/KeccakP-1600-times2/AVX512/KeccakP-1600-times2-SIMD512.c:194:9: note: in expansion of macro ‘Add_In4’
  194 |         Add_In4( 0 );
      |         ^~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:55,
                 from lib/low/KeccakP-1600-times2/AVX512/KeccakP-1600-times2-SIMD512.c:28:
/usr/lib/gcc/x86_64-linux-gnu/10/include/avx512fintrin.h:7443:1: error: inlining failed in call to ‘always_inline’ ‘_mm512_xor_si512’: target specific option mismatch
 7443 | _mm512_xor_si512 (__m512i __A, __m512i __B)
      | ^~~~~~~~~~~~~~~~
lib/low/KeccakP-1600-times2/AVX512/KeccakP-1600-times2-SIMD512.c:125:37: note: called from here
  125 | #define XOR512(a,b)                 _mm512_xor_si512(a,b)
      |                                     ^~~~~~~~~~~~~~~~~~~~~
lib/low/KeccakP-1600-times2/AVX512/KeccakP-1600-times2-SIMD512.c:192:64: note: in expansion of macro ‘XOR512’
  192 |     #define Add_In4( argIndex )  stateAsLanes512[argIndex/4] = XOR512(stateAsLanes512[argIndex/4], LOAD_GATHER8_64(index512, dataAsLanes+argIndex))
      |                                                                ^~~~~~
lib/low/KeccakP-1600-times2/AVX512/KeccakP-1600-times2-SIMD512.c:197:9: note: in expansion of macro ‘Add_In4’
  197 |         Add_In4( 12 );
      |         ^~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/include/immintrin.h:55,
                 from lib/low/KeccakP-1600-times2/AVX512/KeccakP-1600-times2-SIMD512.c:28:
/usr/lib/gcc/x86_64-linux-gnu/10/include/avx512fintrin.h:10255:1: error: inlining failed in call to ‘always_inline’ ‘_mm512_i32gather_epi64’: target specific option mismatch
10255 | _mm512_i32gather_epi64 (__m256i __index, void const *__addr, int __scale)
      | ^~~~~~~~~~~~~~~~~~~~~~
lib/low/KeccakP-1600-times2/AVX512/KeccakP-1600-times2-SIMD512.c:125:37: note: called from here
  125 | #define XOR512(a,b)                 _mm512_xor_si512(a,b)
      |                                     ^~~~~~~~~~~~~~~~~~~~~
lib/low/KeccakP-1600-times2/AVX512/KeccakP-1600-times2-SIMD512.c:192:64: note: in expansion of macro ‘XOR512’
  192 |     #define Add_In4( argIndex )  stateAsLanes512[argIndex/4] = XOR512(stateAsLanes512[argIndex/4], LOAD_GATHER8_64(index512, dataAsLanes+argIndex))
      |                                                                ^~~~~~
lib/low/KeccakP-1600-times2/AVX512/KeccakP-1600-times2-SIMD512.c:197:9: note: in expansion of macro ‘Add_In4’
  197 |         Add_In4( 12 );
      |         ^~~~~~~
`

The pair of errors (`_mm512_xor_si512` and `_mm512_i32gather_epi64`) happen four times, but I assume these are all the same basic problem.

**Comment by larryhastings** [comment]
This is with a current checkout of XKCP (revision cf2a63166998349447539626ea08c27a44f4857e).

Gee whiz, Github turned the error message into complete hash.  I'll attach a file of the log here.

[keccak.avs512.gcc.linux.errors.txt](https://github.com/XKCP/XKCP/files/5978865/keccak.avs512.gcc.linux.errors.txt)

**Comment by larryhastings** [comment]
In case it helps, AVX2 builds and works fine.

**Comment by gvanas** [comment]
Strange, these targets build fine with GCC on my Linux machine. Can you give more details about your system (processor, GCC version)?

It seems to complain about the support of AVX512F. Does your processor support this subset?

**Comment by larryhastings** [comment]
My computer is running Pop!_OS 20.10, a tweaked variant of Ubuntu.  It currently provides gcc 10.2.0.

My processor (AMD Ryzen 5950X) doesn't support AVX512 at all, the highest it goes is AVX2.

Ah, I see!  The problem is, XKCP's makefile specifies "-march=native", even when I've specifically requested it build an AVX512 variant.  This makes it impossible for me to cross-compile versions of XKCP for other SIMD instruction sets.  If I want to compile XKCP for AVX512, I am forced to compile it on a computer which supports AVX512.

Should I assume this is working as intended, then?

**Comment by gvanas** [comment]
You can cross-compile by adding the appropriate compilation options. The easiest is to do it locally when invoking make:
```
make AVX512/KeccakSum CC="gcc -mavx512f -mavx512vl"
```

My intention is to add runtime instruction set selection, like in [K12](https://github.com/XKCP/K12/), but I just haven't found the time to do that yet (*help welcome*).
