### ISSUE TITLE
Kravatte segfaults

### ISSUE THREAD

**Issue by sebastianv89** [XKCP/XKCP#81]
On AVX2, the UnitTests and Benchmarks of Kravatte give a segmentation fault.

Easiest way to reproduce:
```
$ make AVX2/UnitTests
$ ./bin/AVX2/UnitTests --Kravatte
```

I'm running on a i5-8265U Intel processor. Let me know if you need more info to be able to reproduce

**Comment by gvanas** [comment]
OK, thanks for the report. I think it is an alignment issue, similar to the one on AVX-512. I will fix this soon.

**Comment by gvanas** [comment]
This should fix the issue. Do not hesitate to reopen if it persists.
