### ISSUE TITLE
Inquiry on Xoodyak

### ISSUE THREAD

**Issue by heesunlee9** [XKCP/XKCP#88]
Hello, 

My name is Heesun Lee, a fourth semester computer science student in Rochester Institute of Technology. I have used Xoodyak as a part of the master project. I need working Xoodyak implementation. Where can I get the implementation? I will add some test code onto the code. I got code 2 ways. 

First, I downloaded Xoodyak code through gihub library (https://github.com/XKCP/XKCP). However, it seems that it is missing something, for example, can I test encryption and decryption using the given code? 

Second, I downloaded code through the NIST homepage. https://csrc.nist.gov/Projects/lightweight-cryptography/finalists (I clicked Zip File of Xoodyak) I had to add an empty header file and there are many functions that are undefined. It seems that it is missing something. Moreover, I don't understand the meaning of each parameter. (For example, what is the meaning of 'k'? Is it a key?) Where can I find the information on parameters? I already read the specification but I could not find any information. Where can I download the full workable implementation?

**Comment by gvanas** [comment]
Dear Heesun Lee,

Thanks for your interest. The XKCP supports Xoodyak and is preferred over the reference implementation if you want to have optimized code.

To use Xoodyak, the interface is documented in [this header file](https://github.com/XKCP/XKCP/blob/master/doc/Xoodyak-documentation.h). Next to that, it is important to understand what these functions do and how to use them properly in your use case. For this, I would advise you to read Sections 1.2 and 3 of our [paper on Xoodyak](https://tosc.iacr.org/index.php/ToSC/article/view/8618).

I hope this helps.

Kind regards,
Gilles
