### ISSUE TITLE
Request for license file

### ISSUE THREAD

**Issue by joshuakraemer** [XKCP/XKCP#99]
I would like to create a KeccakSum package for a Linux distribution (draft at https://github.com/joshuakraemer/void-packages/blob/new-package-XKCP/srcpkgs/XKCP/template).

The licenses specified in your readme file require binary redistributions to include the license texts. Could you please provide a license file (or several license files) containing the pertinent license texts suitable for packaging?

**Comment by joshuakraemer** [comment]
Thank you very much, the new license file is fine, I also appreciate the hints about usage of the relevant files in each component!

**Comment by gvanas** [comment]
OK, cool! I just merged to master.
